# Generated by Django 4.1.2 on 2023-03-27 12:05

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='body_art_consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_code', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(default='add summary', max_length=255)),
                ('consent', djrichtextfield.models.RichTextField()),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
