# Generated by Django 4.1.2 on 2023-04-03 18:24

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_body_art_consent_consent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tattoo_consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_code', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consent', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
