# Generated by Django 4.1.2 on 2023-02-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aftercare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='microbladingService',
        ),
        migrations.DeleteModel(
            name='piercingsService',
        ),
        migrations.DeleteModel(
            name='pmuService',
        ),
        migrations.DeleteModel(
            name='tattooService',
        ),
    ]
