# Generated by Django 4.1.2 on 2023-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pmuService',
            new_name='services',
        ),
        migrations.DeleteModel(
            name='microbladingService',
        ),
        migrations.DeleteModel(
            name='piercingsService',
        ),
        migrations.DeleteModel(
            name='tattooService',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
    ]
