# Generated by Django 4.1.2 on 2023-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_pmuservice_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(default='add description', max_length=255),
        ),
    ]
