# Generated by Django 4.1.2 on 2023-03-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='summary',
        ),
    ]
