# Generated by Django 4.1.2 on 2023-03-03 09:31

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_description_services_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=djrichtextfield.models.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
