# Generated by Django 4.1.2 on 2022-12-31 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
